/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/home/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/home/AppHeader.vue')['default']
    CustomizeTitle: typeof import('./src/components/CustomizeTitle.vue')['default']
    FloatingTools: typeof import('./src/components/FloatingTools.vue')['default']
    GridBackground: typeof import('./src/components/GridBackground.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    MouseCursor: typeof import('./src/components/MouseCursor.vue')['default']
    RandomBackground: typeof import('./src/components/RandomBackground.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteRuntime: typeof import('./src/components/SiteRuntime.vue')['default']
    Typewriter: typeof import('./src/components/Typewriter.vue')['default']
    VerticalNav: typeof import('./src/components/VerticalNav.vue')['default']
    WebSetting: typeof import('./src/components/dialog/WebSetting.vue')['default']
  }
}
